from django.urls import path

from . import views

# URLs del portal:
# - "/"           landing pública
# - "/intranet/"  acceso oculto (sin link público en el landing salvo el candadito del header)
# - "/intranet/captcha/"  AJAX para regenerar el captcha
# - "/intranet/salir/"    logout (solo POST)
# - "/intranet/bandeja/"          bandeja del usuario logueado
# - "/intranet/correo/<id>/"      detalle de un correo
urlpatterns = [
    path('healthz',                          views.healthz_view,      name='healthz'),
    path('',                                 views.landing_view,      name='landing'),
    path('privacidad/',                      views.privacidad_view,   name='privacidad'),
    path('intranet/',                        views.login_view,        name='login'),
    path('intranet/captcha/',                views.captcha_regenerar,    name='captcha_regenerar'),
    path('intranet/cambiar-password/',       views.cambiar_password_view, name='cambiar_password'),
    path('intranet/2fa/setup/',              views.setup_2fa_view,        name='setup_2fa'),
    path('intranet/2fa/verify/',             views.verify_2fa_view,       name='verify_2fa'),
    path('intranet/2fa/codigos/',            views.mostrar_recovery_codes_view, name='mostrar_recovery_codes'),
    path('intranet/2fa/codigos/confirmar/',  views.confirmar_recovery_codes_view, name='confirmar_recovery_codes'),
    path('intranet/2fa/codigos/pdf/',        views.descargar_recovery_pdf_view, name='descargar_recovery_pdf'),
    path('intranet/2fa/regenerar/',          views.regenerar_recovery_codes_view, name='regenerar_recovery_codes'),
    path('intranet/buzon/cambiar/',          views.cambiar_buzon_view,    name='cambiar_buzon'),
    path('intranet/salir/',                  views.logout_view,       name='logout'),
    path('intranet/escritorio/',             views.escritorio_view,   name='escritorio'),
    path('intranet/bandeja/',                views.inbox_view,        name='inbox'),
    path('intranet/correo/<int:correo_id>/preview/',     views.correo_preview_view,   name='correo_preview'),
    path('intranet/correo/<int:correo_id>/prefill/',     views.correo_prefill_view,   name='correo_prefill'),
    path('intranet/correo/<int:correo_id>/destacar/',    views.toggle_destacado_view, name='toggle_destacado'),
    path('intranet/correo/<int:correo_id>/leido/',       views.toggle_leido_view,     name='toggle_leido'),
    path('intranet/correo/<int:correo_id>/snooze/',      views.snooze_correo_view,    name='snooze_correo'),
    path('intranet/correo/<int:correo_id>/unsnooze/',    views.unsnooze_correo_view,  name='unsnooze_correo'),
    path('intranet/correo/<int:correo_id>/eliminar/',    views.correo_eliminar_view,           name='correo_eliminar'),
    path('intranet/correo/<int:correo_id>/restaurar/',   views.correo_restaurar_view,          name='correo_restaurar'),
    path('intranet/correo/<int:correo_id>/eliminar-permanente/', views.correo_eliminar_permanente_view, name='correo_eliminar_permanente'),
    path('intranet/papelera-correos/',                   views.papelera_correos_view,          name='papelera_correos'),
    path('intranet/papelera-correos/vaciar/',            views.vaciar_papelera_view,           name='vaciar_papelera'),
    path('intranet/correos/bulk-eliminar/',              views.correo_bulk_eliminar_view,      name='correo_bulk_eliminar'),
    path('intranet/correo/<int:correo_id>/notas/',       views.actualizar_notas_view, name='actualizar_notas'),
    path('intranet/correo/<int:correo_id>/etiqueta/',    views.asignar_etiqueta_view, name='asignar_etiqueta'),
    path('intranet/correo/<int:correo_id>/reenviar/',    views.reenviar_correo_view,  name='reenviar_correo'),
    path('intranet/correo/<int:correo_id>/responder/',   views.responder_correo_view, name='responder_correo'),
    path('intranet/correo/<int:correo_id>/cid/<str:content_id>',  views.adjunto_por_cid_view,  name='adjunto_por_cid'),
    path('intranet/correo/<int:correo_id>/',             views.detalle_view,          name='detalle'),
    path('intranet/adjunto/<int:adjunto_id>/',           views.adjunto_view,          name='adjunto'),
    path('intranet/buzon/etiqueta-nueva/',               views.crear_etiqueta_view,   name='crear_etiqueta'),
    path('intranet/buzon/firma/',                        views.firma_view,            name='firma'),
    path('intranet/correos/bulk/',                       views.bulk_acciones_view,    name='bulk_acciones'),
    path('intranet/contactos/',                          views.contactos_view,        name='contactos'),
    path('intranet/redactar/',                           views.compose_view,          name='compose'),
    path('intranet/borradores/',                         views.borradores_view,           name='borradores'),
    path('intranet/borradores/<int:borrador_id>/',       views.borrador_detalle_view,     name='borrador_detalle'),
    path('intranet/borradores/<int:borrador_id>/enviar/', views.borrador_enviar_view,     name='borrador_enviar'),
    path('intranet/borradores/<int:borrador_id>/adjuntos/',              views.borrador_adjunto_upload_view, name='borrador_adjunto_upload'),
    path('intranet/borradores/<int:borrador_id>/adjuntos/<int:adj_id>/', views.borrador_adjunto_delete_view, name='borrador_adjunto_delete'),

    # ─── Apps Archivos / Contratos / Papelera (Fase 2) ────────────────────
    path('intranet/archivos/',                                  views.archivos_list_view,             name='archivos'),
    path('intranet/archivos/subir/',                            views.archivos_upload_view,           name='archivos_upload'),
    path('intranet/archivos/<int:archivo_id>/descargar/',       views.archivo_descargar_view,         name='archivo_descargar'),
    path('intranet/archivos/<int:archivo_id>/borrar/',          views.archivo_borrar_view,            name='archivo_borrar'),
    path('intranet/archivos/<int:archivo_id>/version/',         views.archivo_subir_version_view,     name='archivo_subir_version'),
    path('intranet/archivos/<int:archivo_id>/compartir/',       views.archivo_compartir_view,         name='archivo_compartir'),
    path('intranet/archivos/<int:archivo_id>/compartir/<int:comparticion_id>/quitar/', views.archivo_descompartir_view, name='archivo_descompartir'),
    path('intranet/correo/<int:correo_id>/vincular-archivo/',                    views.correo_vincular_archivo_view,    name='correo_vincular_archivo'),
    path('intranet/correo/<int:correo_id>/vincular-archivo/<int:vinculo_id>/quitar/', views.correo_desvincular_archivo_view, name='correo_desvincular_archivo'),
    path('intranet/contratos/',                                 views.contratos_list_view,            name='contratos'),
    path('intranet/papelera/',                                  views.papelera_list_view,             name='papelera'),
    path('intranet/papelera/<int:archivo_id>/restaurar/',       views.archivo_restaurar_view,         name='archivo_restaurar'),
    path('intranet/papelera/<int:archivo_id>/borrar-permanente/', views.archivo_borrar_permanente_view, name='archivo_borrar_permanente'),

    # ─── Campañas de correos automáticos ─────────────────────────────────────
    path('intranet/campanas/',                                  views.campanas_list_view,             name='campanas'),
    path('intranet/campanas/nueva/',                            views.campana_crear_view,             name='campana_crear'),
    path('intranet/campanas/<int:campana_id>/',                 views.campana_editar_view,            name='campana_editar'),
    path('intranet/campanas/<int:campana_id>/eliminar/',        views.campana_eliminar_view,          name='campana_eliminar'),
    path('intranet/campanas/<int:campana_id>/toggle/',          views.campana_toggle_view,            name='campana_toggle'),
    path('intranet/campanas/<int:campana_id>/test/',            views.campana_test_view,              name='campana_test'),
    path('intranet/campanas/<int:campana_id>/preview/',         views.campana_preview_view,           name='campana_preview'),
    path('intranet/campanas/<int:campana_id>/ejecutar/',        views.campana_ejecutar_view,          name='campana_ejecutar'),
    path('intranet/campanas/<int:campana_id>/envios.json',      views.campana_envios_json_view,       name='campana_envios_json'),
    path('intranet/campanas/listas/nueva/',                     views.lista_crear_view,               name='lista_crear'),
    path('intranet/campanas/listas/<int:lista_id>/',            views.lista_editar_view,              name='lista_editar'),
    path('intranet/campanas/listas/<int:lista_id>/eliminar/',   views.lista_eliminar_view,            name='lista_eliminar'),
    path('intranet/campanas/listas/<int:lista_id>/contactos/',  views.contacto_agregar_view,          name='contacto_agregar'),
    path('intranet/campanas/listas/<int:lista_id>/import/',     views.contactos_importar_csv_view,    name='contactos_importar'),
    path('intranet/campanas/contactos/<int:contacto_id>/eliminar/', views.contacto_eliminar_view,     name='contacto_eliminar'),

    # ─── Taller: gestión catálogo + agenda desde el escritorio ───────────────
    path('intranet/taller/<str:tipo>/',                          views.taller_items_list_view,         name='taller_items_list'),
    path('intranet/taller/<str:tipo>/nuevo/',                    views.taller_item_form_view,          name='taller_item_crear'),
    path('intranet/taller/<str:tipo>/<int:item_id>/',            views.taller_item_form_view,          name='taller_item_editar'),
    path('intranet/taller/item/<int:item_id>/eliminar/',         views.taller_item_eliminar_view,      name='taller_item_eliminar'),
    path('intranet/taller/item/<int:item_id>/toggle/',           views.taller_item_toggle_view,        name='taller_item_toggle'),
    path('intranet/taller/agenda/',                              views.taller_agenda_view,             name='taller_agenda'),
    path('intranet/taller/reserva/<int:reserva_id>/',            views.taller_reserva_detalle_view,    name='taller_reserva_detalle'),
    path('intranet/taller/reserva/<int:reserva_id>/confirmar/',  views.taller_reserva_confirmar_view,  name='taller_reserva_confirmar'),
    path('intranet/taller/reserva/<int:reserva_id>/cancelar/',   views.taller_reserva_cancelar_view,   name='taller_reserva_cancelar'),
    path('intranet/taller/reserva/<int:reserva_id>/completar/',  views.taller_reserva_completar_view,  name='taller_reserva_completar'),
]
