# Generated by Django 5.0.4 on 2026-04-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buzon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('total_correos', models.IntegerField(default=0)),
                ('importado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buzón',
                'verbose_name_plural': 'Buzones',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_id', models.CharField(blank=True, db_index=True, max_length=500)),
                ('remitente', models.CharField(blank=True, max_length=500)),
                ('destinatario', models.TextField(blank=True)),
                ('asunto', models.CharField(blank=True, max_length=1000)),
                ('fecha', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cuerpo_texto', models.TextField(blank=True)),
                ('tiene_adjunto', models.BooleanField(default=False)),
                ('buzon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='correos.buzon')),
            ],
            options={
                'verbose_name': 'Correo',
                'verbose_name_plural': 'Correos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['buzon', '-fecha'], name='correos_cor_buzon_i_0f9be3_idx')],
            },
        ),
    ]
