# Generated by Django 6.0.4 on 2026-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('email_intentado', models.CharField(blank=True, max_length=254)),
                ('captcha_categoria', models.CharField(blank=True, max_length=30)),
                ('tiempo_ms', models.IntegerField(default=0)),
                ('honeypot_lleno', models.BooleanField(default=False)),
                ('exito', models.BooleanField(db_index=True, default=False)),
                ('motivo', models.CharField(blank=True, choices=[('exito', 'Login exitoso'), ('honeypot', 'Honeypot lleno'), ('muy_rapido', 'Tiempo sospechosamente bajo'), ('captcha_fail', 'Captcha incorrecto/expirado'), ('email_no_lista', 'Email fuera de allowlist'), ('buzon_inexist', 'Buzón no importado'), ('email_invalido', 'Formato de email inválido'), ('throttled', 'Bloqueado por rate-limit'), ('csrf', 'CSRF inválido')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Intento de login',
                'verbose_name_plural': 'Intentos de login',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['ip_hash', '-creado'], name='correos_int_ip_hash_bc0957_idx'), models.Index(fields=['exito', '-creado'], name='correos_int_exito_78d97e_idx')],
            },
        ),
    ]
