# Generated by Django 6.0.4 on 2026-05-05 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0002_intentologin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('es_admin', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario del portal',
                'verbose_name_plural': 'Usuarios del portal',
                'ordering': ['email'],
            },
        ),
        migrations.AlterField(
            model_name='intentologin',
            name='motivo',
            field=models.CharField(blank=True, choices=[('exito', 'Login exitoso'), ('honeypot', 'Honeypot lleno'), ('muy_rapido', 'Tiempo sospechosamente bajo'), ('captcha_fail', 'Captcha incorrecto/expirado'), ('email_no_lista', 'Email fuera de allowlist'), ('email_invalido', 'Formato de email inválido'), ('password_invalida', 'Contraseña incorrecta'), ('usuario_inactivo', 'Usuario marcado inactivo'), ('buzon_inexist', 'Buzón no importado'), ('throttled', 'Bloqueado por rate-limit'), ('csrf', 'CSRF inválido')], max_length=20),
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=300)),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='correos.correo')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['nombre_original'],
                'indexes': [models.Index(fields=['correo'], name='correos_adj_correo__2f8a1f_idx')],
            },
        ),
    ]
