# Generated by Django 6.0.4 on 2026-05-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0003_usuarioportal_alter_intentologin_motivo_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioportal',
            name='buzones',
            field=models.ManyToManyField(blank=True, help_text='Buzones que este usuario puede consultar (ignorado para admins).', related_name='usuarios', to='correos.buzon'),
        ),
        migrations.AlterField(
            model_name='usuarioportal',
            name='es_admin',
            field=models.BooleanField(default=False, help_text='Si está marcado, ve TODOS los buzones (la lista de buzones se ignora).'),
        ),
    ]
