# Generated by Django 6.0.4 on 2026-05-05 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0004_usuarioportal_buzones_alter_usuarioportal_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='destacado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='correo',
            name='notas',
            field=models.TextField(blank=True, help_text='Anotaciones internas del equipo (máx 5000 chars).', max_length=5000),
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('color', models.CharField(choices=[('#C80C0F', 'Rojo'), ('#1976D2', 'Azul'), ('#388E3C', 'Verde'), ('#F57C00', 'Naranja'), ('#7B1FA2', 'Morado'), ('#5D4037', 'Café'), ('#455A64', 'Grafito'), ('#FBC02D', 'Amarillo')], default='#C80C0F', max_length=7)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('buzon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='correos.buzon')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='correo',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='correos', to='correos.etiqueta'),
        ),
        migrations.AddIndex(
            model_name='correo',
            index=models.Index(fields=['buzon', 'destacado'], name='correos_cor_buzon_i_bd1323_idx'),
        ),
        migrations.AddIndex(
            model_name='etiqueta',
            index=models.Index(fields=['buzon', 'nombre'], name='correos_eti_buzon_i_179905_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etiqueta',
            unique_together={('buzon', 'nombre')},
        ),
    ]
