# Generated by Django 5.2.14 on 2026-05-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0026_archivo_versiones_comparticion_vinculo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='correo',
            new_name='correos_cor_buzon_i_a5d3a1_idx',
            old_name='correos_cor_buzon_i_2c8a4f_idx',
        ),
        migrations.RenameIndex(
            model_name='reenviocorreo',
            new_name='correos_ree_usuario_5e8270_idx',
            old_name='correos_ree_usuario_a8c3f1_idx',
        ),
        migrations.RenameIndex(
            model_name='reenviocorreo',
            new_name='correos_ree_exito_1859e7_idx',
            old_name='correos_ree_exito_b2d96e_idx',
        ),
        migrations.AlterField(
            model_name='archivocomparticion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='archivovinculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
