# Generated by Django 5.2.14 on 2026-05-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0035_usuarioportal_puede_taller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoauditoria',
            name='accion',
            field=models.CharField(choices=[('login_ok', 'Login exitoso'), ('logout', 'Logout'), ('account_lockout', 'Cuenta bloqueada por brute-force'), ('password_cambio', 'Cambio de password'), ('totp_setup', '2FA configurado'), ('totp_reset', '2FA reseteado'), ('recovery_regen', 'Recovery codes regenerados'), ('bulk_leer', 'Marcar leídos en masa'), ('bulk_no_leer', 'Marcar no-leídos en masa'), ('bulk_destacar', 'Destacar en masa'), ('bulk_etiquetar', 'Etiquetar en masa'), ('snooze', 'Posponer correo'), ('unsnooze', 'Cancelar snooze'), ('etiqueta_crear', 'Etiqueta creada'), ('etiqueta_asignar', 'Etiqueta asignada a correo'), ('etiqueta_quitar', 'Etiqueta quitada de correo'), ('firma_actualizar', 'Firma del buzón actualizada'), ('borrador_crear', 'Borrador creado'), ('borrador_borrar', 'Borrador descartado')], db_index=True, max_length=30),
        ),
    ]
