# Generated by Django 5.2.14 on 2026-05-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itemcatalogo',
            new_name='taller_item_activo_1da546_idx',
            old_name='taller_item_activo__19a76e_idx',
        ),
        migrations.RenameIndex(
            model_name='itemcatalogo',
            new_name='taller_item_destaca_6e649a_idx',
            old_name='taller_item_destaca_8b3f9c_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='taller_rese_fecha_47b2e3_idx',
            old_name='taller_reser_fecha_h_3c8a2d_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='taller_rese_estado_07e8c1_idx',
            old_name='taller_reser_estado_5e7b91_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='taller_rese_cliente_bcbaab_idx',
            old_name='taller_reser_client_2a9f4c_idx',
        ),
        migrations.RenameIndex(
            model_name='reservaintento',
            new_name='taller_rese_ip_hash_0331e9_idx',
            old_name='taller_resi_ip_hash_4a2c8e_idx',
        ),
        migrations.RenameIndex(
            model_name='reservaintento',
            new_name='taller_rese_exito_4e1d3b_idx',
            old_name='taller_resi_exito_d5b1f7_idx',
        ),
    ]
